"""
Vintage Data Validator

Validates vintage data provenance to prevent accidental use of synthetic test data
in production pipelines.

CRITICAL: This module protects production pipelines from synthetic data contamination.
"""

from pathlib import Path
from typing import Optional
import pandas as pd
from loguru import logger


class VintageValidationError(Exception):
    """Raised when vintage data fails production validation"""
    pass


def validate_vintage_is_production(
    df: pd.DataFrame,
    vintage_path: Path,
    allow_test_data: bool = False,
    strict: bool = True
) -> None:
    """
    Validate that vintage data is from production ETL, not synthetic test data.
    
    This function performs multiple checks to detect synthetic test data:
    1. Check parquet metadata for is_synthetic flag
    2. Check for suspiciously small datasets
    3. Check for test data pinned date (2024-01-15)
    4. Check for test data row count (120 rows)
    
    Args:
        df: DataFrame to validate
        vintage_path: Path to the vintage file (for error messages)
        allow_test_data: If True, log warnings instead of raising errors
        strict: If True, apply stricter validation (recommended for production)
        
    Raises:
        VintageValidationError: If data appears to be synthetic test data
        
    Example:
        ```python
        df = pd.read_parquet("data/vintages/bls_ces/2024-11-16/bls_ces_vintage.parquet")
        validate_vintage_is_production(df, Path(vintage_path))
        ```
    """
    
    # Check 1: Parquet metadata flag (most reliable)
    if hasattr(df, 'attrs'):
        is_synthetic = df.attrs.get('is_synthetic', None)
        
        if is_synthetic is True:
            error_msg = (
                f"❌ SYNTHETIC TEST DATA DETECTED\n"
                f"   File: {vintage_path}\n"
                f"   Generated by: {df.attrs.get('generated_by', 'unknown')}\n"
                f"   Purpose: {df.attrs.get('purpose', 'unknown')}\n"
                f"   Warning: {df.attrs.get('warning', 'N/A')}\n"
                f"\n"
                f"   🔴 CRITICAL: Cannot run production pipeline on synthetic data!\n"
                f"   ✅ Solution: Run 'make seed' to generate production vintages"
            )
            
            if allow_test_data:
                logger.warning(error_msg)
                return
            else:
                logger.error(error_msg)
                raise VintageValidationError(error_msg)
        
        elif is_synthetic is False:
            # Confirmed production data
            logger.info(f"✅ Vintage validated as PRODUCTION data: {vintage_path}")
            logger.debug(f"   Generated by: {df.attrs.get('generated_by', 'unknown')}")
            logger.debug(f"   Vintage date: {df.attrs.get('vintage_date', 'unknown')}")
            return
        
        else:
            # No metadata flag found
            if strict:
                warning_msg = (
                    f"⚠️  MISSING PROVENANCE METADATA\n"
                    f"   File: {vintage_path}\n"
                    f"   The 'is_synthetic' flag is not set in parquet metadata.\n"
                    f"   This might be from an older ETL version or manually created file.\n"
                    f"   ⚠️  Proceeding with additional checks..."
                )
                logger.warning(warning_msg)
            else:
                logger.debug(f"No metadata flag found for {vintage_path}, proceeding with heuristic checks")
    
    # Check 2 & 3 Combined: Test data pinned date + row count (check together for better error)
    TEST_DATA_ROW_COUNT = 120
    TEST_PINNED_DATE = "2024-01-15"
    has_test_row_count = len(df) == TEST_DATA_ROW_COUNT
    has_test_pinned_date = TEST_PINNED_DATE in str(vintage_path)
    
    # Check for MULTIPLE indicators first (highest confidence)
    if has_test_pinned_date and has_test_row_count and strict and not allow_test_data:
        error_msg = (
            f"❌ MULTIPLE TEST DATA INDICATORS\n"
            f"   File: {vintage_path}\n"
            f"   - Pinned test date: {TEST_PINNED_DATE}\n"
            f"   - Test row count: {len(df)} rows\n"
            f"   🔴 HIGH CONFIDENCE: This is synthetic test data!"
        )
        logger.error(error_msg)
        raise VintageValidationError(error_msg)
    
    # Check pinned date alone (medium confidence)
    if has_test_pinned_date:
        warning_msg = (
            f"⚠️  Test data pinned date detected: {TEST_PINNED_DATE}\n"
            f"   File: {vintage_path}\n"
            f"   This is the standard date for synthetic test data.\n"
            f"   ⚠️  Confirm this is intentional production use."
        )
        logger.warning(warning_msg)
    
    # Check suspicious row count alone (medium confidence)
    if has_test_row_count:
        error_msg = (
            f"⚠️  SUSPICIOUS: Dataset has exactly {TEST_DATA_ROW_COUNT} rows\n"
            f"   File: {vintage_path}\n"
            f"   This matches the synthetic test data row count.\n"
            f"   ⚠️  High probability this is synthetic test data!"
        )
        
        if strict and not allow_test_data and not has_test_pinned_date:
            # Only raise for row count if we didn't already check pinned date above
            logger.error(error_msg)
            raise VintageValidationError(error_msg)
        else:
            logger.warning(error_msg)
    
    elif len(df) < 50:
        logger.warning(
            f"⚠️  Small dataset ({len(df)} rows) detected: {vintage_path}\n"
            f"   Verify this is legitimate production data."
        )
    
    # Check 4: Path contains "test" keyword
    if "test" in str(vintage_path).lower() and "test" not in "latest":
        logger.warning(
            f"⚠️  Path contains 'test' keyword: {vintage_path}\n"
            f"   Verify this is production data."
        )
    
    # If we get here without errors, log success
    if strict:
        logger.info(
            f"✅ Vintage validation passed (heuristics): {vintage_path}\n"
            f"   Rows: {len(df)}, Columns: {len(df.columns)}\n"
            f"   ⚠️  Note: No metadata flag found, relied on heuristics"
        )
    else:
        logger.debug(f"Vintage validation passed: {vintage_path}")


def require_production_data(df: pd.DataFrame, vintage_path: Path) -> None:
    """
    Strict validation that REQUIRES production data (synthetic data always fails).
    
    Use this in production pipelines where synthetic data must never be used.
    
    Args:
        df: DataFrame to validate
        vintage_path: Path to the vintage file
        
    Raises:
        VintageValidationError: If data is synthetic or validation fails
    """
    validate_vintage_is_production(
        df=df,
        vintage_path=vintage_path,
        allow_test_data=False,
        strict=True
    )


def get_vintage_provenance(df: pd.DataFrame) -> dict:
    """
    Extract provenance metadata from vintage DataFrame.
    
    Args:
        df: DataFrame to extract metadata from
        
    Returns:
        dict: Provenance metadata (empty if none found)
    """
    if not hasattr(df, 'attrs'):
        return {}
    
    return {
        'is_synthetic': df.attrs.get('is_synthetic'),
        'generated_by': df.attrs.get('generated_by'),
        'generation_date': df.attrs.get('generation_date'),
        'purpose': df.attrs.get('purpose'),
        'source_name': df.attrs.get('source_name'),
        'vintage_date': df.attrs.get('vintage_date'),
        'warning': df.attrs.get('warning'),
        'random_seed': df.attrs.get('random_seed'),
    }


def is_synthetic_data(df: pd.DataFrame) -> Optional[bool]:
    """
    Check if DataFrame contains synthetic test data.
    
    Args:
        df: DataFrame to check
        
    Returns:
        True if synthetic, False if production, None if unknown
    """
    if hasattr(df, 'attrs'):
        return df.attrs.get('is_synthetic')
    return None


def log_vintage_provenance(df: pd.DataFrame, vintage_path: Path) -> None:
    """
    Log provenance information for a vintage DataFrame.
    
    Args:
        df: DataFrame to log metadata for
        vintage_path: Path to the vintage file
    """
    provenance = get_vintage_provenance(df)
    
    if not provenance or all(v is None for v in provenance.values()):
        logger.warning(
            f"⚠️  No provenance metadata found: {vintage_path}\n"
            f"   Consider regenerating with updated ETL"
        )
        return
    
    is_synthetic = provenance.get('is_synthetic')
    
    if is_synthetic is True:
        logger.warning(
            f"🏷️  SYNTHETIC TEST DATA\n"
            f"   File: {vintage_path}\n"
            f"   Generated by: {provenance.get('generated_by')}\n"
            f"   Purpose: {provenance.get('purpose')}\n"
            f"   Date: {provenance.get('generation_date')}"
        )
    elif is_synthetic is False:
        logger.info(
            f"🏷️  PRODUCTION DATA\n"
            f"   File: {vintage_path}\n"
            f"   Generated by: {provenance.get('generated_by')}\n"
            f"   Source: {provenance.get('source_name')}\n"
            f"   Vintage: {provenance.get('vintage_date')}\n"
            f"   Date: {provenance.get('generation_date')}"
        )
    else:
        logger.warning(f"⚠️  Unknown provenance: {vintage_path}")


def save_vintage_with_metadata(df: pd.DataFrame, path: Path) -> None:
    """
    Save DataFrame to parquet with attrs metadata preserved.
    
    Pandas doesn't preserve DataFrame.attrs by default when writing parquet.
    This function manually stores attrs as parquet file metadata.
    
    Args:
        df: DataFrame with attrs metadata to save
        path: Path to save parquet file
        
    Example:
        ```python
        df = pd.DataFrame({"value": [1, 2, 3]})
        df.attrs['is_synthetic'] = False
        df.attrs['generated_by'] = 'etl.bls_ces'
        save_vintage_with_metadata(df, Path("data/vintages/ces/data.parquet"))
        ```
    """
    import pyarrow as pa
    import pyarrow.parquet as pq
    
    # Convert DataFrame to Arrow table
    table = pa.Table.from_pandas(df)
    
    # Extract attrs and convert to metadata
    if hasattr(df, 'attrs') and df.attrs:
        # Convert attrs values to strings for metadata storage
        metadata_dict = {
            key: str(value) if value is not None else ""
            for key, value in df.attrs.items()
        }
        
        # Merge with existing metadata
        existing_metadata = table.schema.metadata or {}
        combined_metadata = {**existing_metadata, **metadata_dict}
        
        # Update table schema with metadata
        table = table.replace_schema_metadata(combined_metadata)
    
    # Write to parquet
    pq.write_table(table, path)
    logger.debug(f"Saved vintage with metadata: {path}")


def load_vintage_with_metadata(path: Path) -> pd.DataFrame:
    """
    Load DataFrame from parquet with attrs metadata restored.
    
    Restores DataFrame.attrs that were saved by save_vintage_with_metadata().
    
    Args:
        path: Path to parquet file
        
    Returns:
        DataFrame with attrs restored
        
    Example:
        ```python
        df = load_vintage_with_metadata(Path("data/vintages/ces/data.parquet"))
        assert df.attrs['is_synthetic'] is False
        ```
    """
    import pyarrow.parquet as pq
    
    # Read parquet with metadata
    table = pq.read_table(path)
    df = table.to_pandas()
    
    # Restore attrs from metadata
    if table.schema.metadata:
        # Convert known keys back to appropriate types
        attrs = {}
        for key_bytes, value_bytes in table.schema.metadata.items():
            key = key_bytes.decode('utf-8') if isinstance(key_bytes, bytes) else key_bytes
            value = value_bytes.decode('utf-8') if isinstance(value_bytes, bytes) else value_bytes
            
            # Convert string back to bool for is_synthetic
            if key == 'is_synthetic':
                if value.lower() == 'true':
                    attrs[key] = True
                elif value.lower() == 'false':
                    attrs[key] = False
                elif value == '':
                    attrs[key] = None
                else:
                    attrs[key] = value
            # Convert string back to int for random_seed
            elif key == 'random_seed':
                try:
                    attrs[key] = int(value) if value else None
                except ValueError:
                    attrs[key] = value
            else:
                attrs[key] = value if value != '' else None
        
        df.attrs = attrs
        logger.debug(f"Loaded vintage with metadata: {path}")
    
    return df

